FROM tensorflow/tensorflow:2.1.0-py3

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get install -y \
    build-essential \
    git \
    libblas-dev \
    libhdf5-serial-dev \
    locales \
    python3-dev \
    tmux \
    vim \
    zsh \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8
ENV TERM=xterm-256color

WORKDIR /src
COPY ./requirements.txt ./requirements-cpu.txt
COPY ./git-requirements.txt ./git-requirements.txt

RUN python -m pip install --upgrade "pip<21" "setuptools<45" wheel
RUN python -m pip install -r requirements-cpu.txt && \
    python -m pip install -r git-requirements.txt
